version: "3.5"

services:
  db:
    image: mariadb:10.11
    volumes:
      - "db-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build: ./
    volumes:
      - "site-data:/var/www/wp-content"
    ports:
      - "8123:80"
    environment:
      DB_HOST: db
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      DB_USER: wordpress
      WORDPRESS_SITE_URL: http://localhost:8123
      FS_METHOD: direct
      # For debugging only:
      #WP_DEBUG: "true"
      #WP_DEBUG_DISPLAY: "true"

volumes:
  db-data:
  site-data:

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.91.0/24
