version: '3.5'

services:
  db:
    image: mariadb:10.3
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    build: ./
    environment:
      DB_HOST: db
      DB_PASSWORD: wordpress
      DB_NAME: wordpress
      DB_USER: wordpress
      WORDPRESS_SITE_URL: http://localhost
      FS_METHOD: direct

  sut:
    image: alpine:3.13
    depends_on:
      - wordpress
    command: /tmp/run_tests.sh
    volumes:
      - "./run_tests.sh:/tmp/run_tests.sh:ro"
